version: '3.7'
networks:
  opengrab-net:
   driver: bridge
services:

# manticore:
#    container_name: manticore
#    image: manticoresearch/manticore
#    #network_mode: host
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#
#    environment:
#      - EXTRA=1
#      - CREATE_PLAIN_TABLES=1
#      #- CREATE_PLAIN_TABLES=sakila_film
#      #- CREATE_PLAIN_TABLES=sakila_film2:0 11 * * *
#      #- CREATE_PLAIN_TABLES=sakila_film2:* * * * *
#
#    restart: always
#    ports:
#      - 9306:9306
#      - 9308:9308
#    ulimits:
#      nproc: 65535
#      nofile:
#         soft: 65535
#         hard: 65535
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./data:/var/lib/manticore
#      - ./manticore.conf:/etc/manticoresearch/manticore.conf # uncomment if you use a custom config
#    networks:
#      - opengrab-net

 srv_rest_api:
    image: my_images/opengrab-api-server:latest
    container_name: og-api-server
    restart: always
    build:
      context: opengrab-api-server
      dockerfile: docker/Dockerfile

    env_file: ./opengrab-api-server/config/local.env
    environment:
      POSTGRES_ADR: host.docker.internal
      STORAGE_MINIO_URL: minio
      BACKEND_PORT: 8081
      BACKEND_URL: 0.0.0.0
      #MANTICORE_ADDR: manticore
      MANTICORE_ADDR: host.docker.internal
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - opengrab-net

    ports:
      - "8081:8081"

     # - "9309:9309"
      #- "9308:9308"
      #- "9306:9306"

