version: '3.7'
networks:
  opengrab-net:
    driver: bridge

services:
 minio:
   image: minio/minio:latest
   command: server --console-address ":9001" /data/
   restart: always
   container_name: og-minio
   ports:
     - "9000:9000"
     - "9001:9001"
   environment:
     MINIO_ROOT_USER: opengrab
     MINIO_ROOT_PASSWORD: minio123
   volumes:
     - minio-storage:/data
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3
   networks:
    - opengrab-net

 tvxml-downloader:
    image: my_images/opengrab-tvxml-downloader:latest
    container_name: og-tvxml-downloader
    restart: always
    build:
      context: opengrab-tvxml-downloader
      dockerfile: docker/Dockerfile

    env_file: ./opengrab-tvxml-downloader/config/local.env
    environment:      
         STORAGE_MINIO_URL: minio
         BACKEND_URL:  	    http://srv_rest_api
         BACKEND_PORT:      8001
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
       minio:
          condition: service_healthy
       srv_rest_api:
          condition: service_started
    networks:
      - opengrab-net

 srv_rest_api:
    image: my_images/opengrab-api-server:latest
    container_name: og-api-server
    restart: always
    build:
      context: opengrab-api-server
      dockerfile: docker/Dockerfile

    env_file: ./opengrab-api-server/config/local.env
    environment:      
         STORAGE_MINIO_URL: minio
         BACKEND_PORT:      8001
         BACKEND_URL:       0.0.0.0
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
#      interval: 30s
#      timeout: 24h
#      retries: 3

    depends_on:
       minio:
          condition: service_healthy
    networks:
      - opengrab-net
    ports:
      - "8001:8001"

  
volumes:
 minio-storage:
